delete from t_code;
insert into t_code values('0101','男');
insert into t_code values('0102','女');
insert into t_code values('0201','级别1');
insert into t_code values('0202','级别2');
insert into t_code values('0203','级别3');
insert into t_code values('0301','动弹');
insert into t_code values('0302','资讯');
insert into t_code values('0303','讨论区');
insert into t_code values('0304','博客');
insert into t_code values('0501','未审核');
insert into t_code values('0502','已审核');
insert into t_code values('0503','已删除');
insert into t_code values('0504','已退回');
commit;