DROP TABLE IF EXISTS T_CAR;

DROP TABLE IF EXISTS T_CAR_PZ;

DROP TABLE IF EXISTS T_CODE;

DROP INDEX IDX_DC_CID ON T_DISCUSS_COMMENTS;

DROP INDEX IDX_DC_RTIME ON T_DISCUSS_COMMENTS;

DROP INDEX IDX_DC_POSTUSER ON T_DISCUSS_COMMENTS;

DROP INDEX IDX_DC_POSTID ON T_DISCUSS_COMMENTS;

DROP TABLE IF EXISTS T_DISCUSS_COMMENTS;

DROP INDEX IDX_DISCUSSPOST_RTIME ON T_DISCUSS_POST;

DROP INDEX IDX_DISCUSSPOST_USER ON T_DISCUSS_POST;

DROP INDEX IDX_DISCUESSPOST_DISID ON T_DISCUSS_POST;

DROP TABLE IF EXISTS T_DISCUSS_POST;

DROP INDEX IDX_DTC_RTIME ON T_DT_COMMENTS;

DROP INDEX IDX_DTC_USERID ON T_DT_COMMENTS;

DROP INDEX IDX_DTC_DTID ON T_DT_COMMENTS;

DROP TABLE IF EXISTS T_DT_COMMENTS;

DROP INDEX IDX_FOLLOW_BEFID ON T_FOLLOW;

DROP INDEX IDX_FOLLOW_FID ON T_FOLLOW;

DROP TABLE IF EXISTS T_FOLLOW;

DROP TABLE IF EXISTS T_MEM_LOG;

DROP INDEX IDX_MOVE_RTIME ON T_MOVE;

DROP INDEX IDX_MOVE_USERID ON T_MOVE;

DROP TABLE IF EXISTS T_MOVE;

DROP INDEX IDX_NEWS_STATUS ON T_NEWS;

DROP INDEX IDX_NEWS_RTIME ON T_NEWS;

DROP INDEX IDX_NEWS_USERID ON T_NEWS;

DROP TABLE IF EXISTS T_NEWS;

DROP INDEX IDX_NEWS_RTIME ON T_NEWS_COMMENTS;

DROP INDEX IDX_NEWS_USERID ON T_NEWS_COMMENTS;

DROP INDEX IDX_NC_NEWID ON T_NEWS_COMMENTS;

DROP TABLE IF EXISTS T_NEWS_COMMENTS;

DROP INDEX IDX_USER_REGTIME ON T_USER;

DROP INDEX IDX_USER_LASTLOGINTIME ON T_USER;

DROP INDEX IDX_USER_URL ON T_USER;

DROP INDEX IDX_USER_NAME ON T_USER;

DROP INDEX IDX_USER_LOGINEMAIL ON T_USER;

DROP TABLE IF EXISTS T_USER;

DROP INDEX IDX_USERCAR_CPZ ON T_USER_CAR;

DROP INDEX IDX_USERCAR_USERID ON T_USER_CAR;

DROP INDEX IDX_USERCAR_CTYPE ON T_USER_CAR;

DROP TABLE IF EXISTS T_USER_CAR;

CREATE TABLE T_CAR
(
  ID                   INT NOT NULL,
  C_TYPE               VARCHAR(50) NOT NULL,
  TYPE_URL             VARCHAR(100) NOT NULL,
  TYPE_PIC             VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID)
);

ALTER TABLE T_CAR COMMENT '车型信息';

CREATE TABLE T_CAR_PZ
(
  ID                   INT NOT NULL,
  CAR_ID               INT NOT NULL,
  PZ_NAME              VARCHAR(50) NOT NULL,
  PZ_URL               VARCHAR(100) NOT NULL,
  PZ_PIC               VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE T_CODE
(
  CODE                 CHAR(4) NOT NULL,
  NAME                 VARCHAR(20) NOT NULL,
  PRIMARY KEY (CODE)
);

CREATE TABLE T_DISCUSS_COMMENTS
(
  ID                   INT NOT NULL AUTO_INCREMENT,
  POSTID               INT NOT NULL,
  USER                 INT NOT NULL,
  COMMENTTIME          DATETIME NOT NULL,
  COMMENT              TEXT NOT NULL,
  COMID                INT COMMENT '可以评论某个评论，如果该字段有值，则说明该条评论是某条评论的评论。',
  PRIMARY KEY (ID)
);

CREATE INDEX IDX_DC_POSTID ON T_DISCUSS_COMMENTS
(
  POSTID
);

CREATE INDEX IDX_DC_POSTUSER ON T_DISCUSS_COMMENTS
(
  USER
);

CREATE INDEX IDX_DC_RTIME ON T_DISCUSS_COMMENTS
(
  COMMENTTIME
);

CREATE INDEX IDX_DC_CID ON T_DISCUSS_COMMENTS
(
  COMID
);

CREATE TABLE T_DISCUSS_POST
(
  ID                   INT NOT NULL AUTO_INCREMENT,
  DISID                INT NOT NULL,
  TITLE                VARCHAR(200) NOT NULL,
  USER                 INT NOT NULL,
  RTIME                DATETIME NOT NULL,
  CONTENT              LONGTEXT NOT NULL,
  REPLY                INT NOT NULL,
  CLICK                INT NOT NULL,
  LAST_REPLY           DATETIME,
  LAST_MAN             INT,
  LAST_ID              INT,
  PRIMARY KEY (ID)
);

ALTER TABLE T_DISCUSS_POST COMMENT '存储所有讨论区的帖子';

CREATE INDEX IDX_DISCUESSPOST_DISID ON T_DISCUSS_POST
(
  DISID
);

CREATE INDEX IDX_DISCUSSPOST_USER ON T_DISCUSS_POST
(
  USER
);

CREATE INDEX IDX_DISCUSSPOST_RTIME ON T_DISCUSS_POST
(
  RTIME
);

CREATE TABLE T_DT_COMMENTS
(
  ID                   INT NOT NULL AUTO_INCREMENT,
  DTID                 INT NOT NULL,
  USER                 INT NOT NULL,
  COMMENTTIME          DATETIME NOT NULL,
  COMMENT              TEXT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE INDEX IDX_DTC_DTID ON T_DT_COMMENTS
(
  DTID
);

CREATE INDEX IDX_DTC_USERID ON T_DT_COMMENTS
(
  USER
);

CREATE INDEX IDX_DTC_RTIME ON T_DT_COMMENTS
(
  COMMENTTIME
);

CREATE TABLE T_FOLLOW
(
  ID                   INT NOT NULL AUTO_INCREMENT,
  FOLLOW               INT NOT NULL,
  BEFOLLOWED           INT NOT NULL,
  RTIME                DATETIME NOT NULL,
  PRIMARY KEY (ID)
);

CREATE INDEX IDX_FOLLOW_FID ON T_FOLLOW
(
  FOLLOW
);

CREATE INDEX IDX_FOLLOW_BEFID ON T_FOLLOW
(
  BEFOLLOWED
);

CREATE TABLE T_MEM_LOG
(
  USERID               INT NOT NULL,
  RTIME                DATETIME NOT NULL,
  CONTENT              VARCHAR(500) NOT NULL
);

CREATE TABLE T_MOVE
(
  ID                   INT NOT NULL AUTO_INCREMENT,
  CONTENT              TEXT NOT NULL,
  USER                 INT NOT NULL,
  RTIME                DATETIME NOT NULL,
  COMMENTS             INT NOT NULL,
  PRIMARY KEY (ID)
);

ALTER TABLE T_MOVE COMMENT '每个人都可以发布动弹。';

CREATE INDEX IDX_MOVE_USERID ON T_MOVE
(
  USER
);

CREATE INDEX IDX_MOVE_RTIME ON T_MOVE
(
  RTIME
);

CREATE TABLE T_NEWS
(
  ID                   INT NOT NULL AUTO_INCREMENT,
  TITLE                VARCHAR(100) NOT NULL,
  SOURCE               VARCHAR(100),
  CONTENT              LONGTEXT NOT NULL,
  SIM_CONTENT          VARCHAR(100) NOT NULL,
  SIM_PIC              VARCHAR(100),
  IS_INDEX             CHAR(1) NOT NULL COMMENT '是：Y
            否：N',
  INDEXPIC             VARCHAR(100),
  INDEXS               VARCHAR(100),
  RELMAN               INT NOT NULL,
  RELTIME              DATETIME NOT NULL,
  STATUS               CHAR(4) NOT NULL COMMENT '0501 未审核
            0502 已审核
            0503 已删除',
  REVIEWMAN            INT,
  REVIEWTIME           DATETIME,
  BACKMAN              INT,
  BACKTIME             DATETIME,
  DELMAN               INT,
  DELTIME              DATETIME,
  REPLY                INT NOT NULL,
  CLICK                INT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE INDEX IDX_NEWS_USERID ON T_NEWS
(
  RELMAN
);

CREATE INDEX IDX_NEWS_RTIME ON T_NEWS
(
  RELTIME
);

CREATE INDEX IDX_NEWS_STATUS ON T_NEWS
(
  STATUS
);

CREATE TABLE T_NEWS_COMMENTS
(
  ID                   INT NOT NULL AUTO_INCREMENT,
  NEWSID               INT NOT NULL,
  USER                 INT NOT NULL,
  COMMENTTIME          DATETIME NOT NULL,
  COMMENT              TEXT NOT NULL,
  SIMPLE               VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE INDEX IDX_NC_NEWID ON T_NEWS_COMMENTS
(
  NEWSID
);

CREATE INDEX IDX_NEWS_USERID ON T_NEWS_COMMENTS
(
  USER
);

CREATE INDEX IDX_NEWS_RTIME ON T_NEWS_COMMENTS
(
  COMMENTTIME
);

CREATE TABLE T_USER
(
  ID                   INT NOT NULL AUTO_INCREMENT,
  LOGIN_EMAIL          VARCHAR(20) NOT NULL COMMENT '唯一',
  NAME                 VARCHAR(20) COMMENT '唯一',
  PASSWORD             VARCHAR(50) NOT NULL,
  GENDER               CHAR(4) NOT NULL COMMENT '代码：
            0101：男
            0102：女',
  PROVINCE             VARCHAR(10) NOT NULL,
  CITY                 VARCHAR(10) NOT NULL,
  URL                  VARCHAR(10),
  SIGN                 VARCHAR(500),
  TITLE                VARCHAR(100),
  REGTIME              DATETIME NOT NULL,
  LASTLOGINTIME        DATETIME,
  PIC                  VARCHAR(100),
  TEL                  VARCHAR(20),
  QQ                   VARCHAR(20),
  ACTIVE_TIME          DATETIME,
  ACTIVE_MAN           INT,
  LEVEL                CHAR(4) NOT NULL,
  FOLLOW               INT NOT NULL,
  BEFOLLOWED           INT NOT NULL,
  CAR_NO               VARCHAR(10) NOT NULL,
  FLAG_NO              INT,
  PRIMARY KEY (ID)
);

ALTER TABLE T_USER COMMENT '注册用户';

CREATE UNIQUE INDEX IDX_USER_LOGINEMAIL ON T_USER
(
  LOGIN_EMAIL
);

CREATE INDEX IDX_USER_NAME ON T_USER
(
  NAME
);

CREATE UNIQUE INDEX IDX_USER_URL ON T_USER
(
  URL
);

CREATE INDEX IDX_USER_LASTLOGINTIME ON T_USER
(
  LASTLOGINTIME
);

CREATE INDEX IDX_USER_REGTIME ON T_USER
(
  REGTIME
);

CREATE TABLE T_USER_CAR
(
  ID                   INT NOT NULL AUTO_INCREMENT,
  USER_ID              INT NOT NULL,
  CTYPE                VARCHAR(50) NOT NULL,
  CPZ                  VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE INDEX IDX_USERCAR_CTYPE ON T_USER_CAR
(
  CTYPE
);

CREATE INDEX IDX_USERCAR_USERID ON T_USER_CAR
(
  USER_ID
);

CREATE INDEX IDX_USERCAR_CPZ ON T_USER_CAR
(
  CPZ
);

